bookkeeper/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # transactions
    path('transactions/', views.TransactionList.as_view(), name='transaction-list'),
    path('transactions/new/', views.TransactionCreate.as_view(), name='transaction-create'),
    path('transactions/<int:pk>/', views.TransactionDetail.as_view(), name='transaction-detail'),
    path('transactions/<int:pk>/edit/', views.TransactionEdit.as_view(), name='transaction-edit'),
    path('transactions/import/', views.TransactionImport.as_view(), name='transaction-import'),
    path('transactions/export/', views.TransactionExport.as_view(), name='transaction-export'),

    # transaction groups
    path('groups/new/', views.TransactionGroupCreate.as_view(), name='transaction-group-create'),
    path('groups/<int:pk>/', views.TransactionGroupDetail.as_view(), name='transaction-group-detail'),

    # accounts
    path('accounts/', views.AccountList.as_view(), name='account-list'),
    path('accounts/export/', views.AccountExport.as_view(), name='account-export'),

    # budgets
    path('budgets/', views.BudgetList.as_view(), name='budget-list'),
    path('budgets/new/', views.BudgetCreate.as_view(), name='budget-create'),
    path('budgets/<slug:code>/', views.BudgetDetail.as_view(), name='budget-detail'),
    path('budgets/<slug:code>/edit/', views.BudgetEdit.as_view(), name='budget-edit'),
]

bookkeeper/forms/account.py
from datetime import datetime
from django import forms
from django.core.exceptions import ValidationError
from csv import reader
from bookkeeper.models import Transaction, Posting


class AccountFilterForm(forms.Form):
    """Account filters."""
    year = forms.ChoiceField(required=False, choices=[('','')])
    stack = forms.BooleanField(required=False, label='Cumulative', initial=False,
        widget=forms.CheckboxInput(attrs={'role':'switch'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['year'].choices = [(None, '-- Year --'),] + [(d.year, d.year) for d in Transaction.objects.dates('date', 'year', order='DESC')]

bookkeeper/forms/budget.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from bookkeeper.models import Budget


class BudgetCreateForm(forms.ModelForm):
    class Meta:
        model = Budget
        fields = ('type', 'name', 'objective', 'supervisor')
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'name'}),
            'objective': forms.TextInput(attrs={'placeholder': 'objective'}),
        }

class BudgetEditForm(forms.ModelForm):
    class Meta:
        model = Budget
        fields = ('name', 'objective', 'supervisor', 'status')


class BudgetFilterForm(forms.Form):

    type = forms.ChoiceField(required=False,
        choices=[(None, '-- Type --')] + Budget._meta.get_field('type').choices,
    )
    supervisor = forms.ModelChoiceField(required=False, empty_label='-- Supervisor --',
        queryset=get_user_model().objects.all(),
    )
    name = forms.CharField(required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Search...'}))
    close = forms.BooleanField(required=False, label='Show closed', initial=False,
        widget=forms.CheckboxInput(attrs={'role':'switch'}))

bookkeeper/forms/transaction.py
from datetime import datetime
from decimal import Decimal
from csv import reader as CSVReader
from django import forms
from django.db import transaction
from django.core.exceptions import ValidationError
from bookkeeper.helpers import TransactionType
from bookkeeper.models import Transaction, TransactionGroup, Budget, Posting, Account


class TransactionBaseForm(forms.ModelForm):
    """Base form for transactions managing the template with the common attributes."""
    class Meta:
        model = Transaction
        fields = ('date', 'payee', 'budget', 'notes', 'evidence', 'evidence_ref')
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'payee': forms.TextInput(attrs={'placeholder': 'Payee'}),
            'evidence_ref': forms.TextInput(attrs={'placeholder': 'Reference'}),
        }

    template_name = 'bookkeeper/forms/transaction_base_form.html'

    def __init__(self, *args, **kwargs):
        """Change model fields behavior."""
        super(TransactionBaseForm, self).__init__(*args, **kwargs)
        self.fields['budget'].empty_label = '-- Budget --'
        self.fields['budget'].required = True
        self.fields['budget'].queryset = Budget.objects.filter(status='O')
        self.fields['evidence'].required = True
        self.fields['evidence_ref'].required = True

    def clean(self):
        """Basic validation for all inherited transaction forms."""
        cleaned_data = super().clean()
        if cleaned_data['budget'].status != 'O':
            raise ValidationError("Can't add or remove transaction on a closed budget.")
        return cleaned_data


class TransactionSimpleForm(TransactionBaseForm):
    """Base form for transaction involving only an amount with taxes."""
    amount = forms.FloatField(required=True, label="Amount", widget=forms.NumberInput(attrs={'placeholder': 'Amount (VAT excl.)'}))
    vat = forms.FloatField(required=True, label="VAT", widget=forms.NumberInput(attrs={'placeholder': 'VAT'}))

    template_name = 'bookkeeper/forms/transaction_simple_form.html'

    def clean(self):
        cleaned_data = super().clean()
        amount = cleaned_data.pop('amount')
        vat = cleaned_data.pop('vat')
        cleaned_data['postings'] = self._helper(amount, vat)
        return cleaned_data

    @transaction.atomic
    def save(self):
        """Save the transaction along with the postings."""
        instance = super().save(commit=True)
        instance.add_postings(self.cleaned_data['postings'])
        instance.clean() # validate model before committing
        return instance


class TransactionSaleForm(TransactionSimpleForm):
    _helper = TransactionType.project_sale


class TransactionOutsourcingForm(TransactionSimpleForm):
    _helper = TransactionType.contractor_expense


class TransactionGeneralForm(TransactionSimpleForm):
    _helper = TransactionType.internal_expense


class TransactionDefrayalForm(TransactionSimpleForm):
    _helper = TransactionType.defrayal_reimbursment


class TransactionVatExpenseForm(TransactionSimpleForm):
    _helper = TransactionType.vat_expense


class TransactionVatCreditForm(TransactionSimpleForm):
    _helper = TransactionType.vat_credit


class TransactionTaxExpenseForm(TransactionSimpleForm):
    _helper = TransactionType.tax_expense


class TransactionManualForm(TransactionBaseForm):
    """Form handling creation of any transaction."""
    template_name = 'bookkeeper/forms/transaction_manual_form.html'

    def __init__(self, *args, **kwargs):
        """Initialize the formset with its fields."""
        super().__init__(*args, **kwargs)
        formset_class = forms.inlineformset_factory(Transaction, Posting,
                fields=['account','amount'], formset=PostingFormSet, extra=1)
        try:
            # FIXME: handle passing initial parameters to formset
            del kwargs['initial']
        except KeyError: pass
        self.formset = formset_class(*args, **kwargs)
        # evidence is not mandatory in manual mode
        self.fields['evidence'].required = False
        self.fields['evidence_ref'].required = False

    def get_context(self):
        """Add the formset to the context for rendering."""
        context = super().get_context()
        context['formset'] = self.formset
        return context

    def is_valid(self):
        return self.formset.is_valid() and super().is_valid()

    def save(self):
        """Bind both models together."""
        instance = super().save(commit=True)
        self.formset.instance = instance
        self.formset.save(commit=True)
        return instance


class PostingFormSet(forms.BaseInlineFormSet):
    """Manage the posting forms in a manual transaction."""
    def _should_delete_form(self, form):
        """Remove postings with null amount or account."""
        if not form.cleaned_data.get('account') or not form.cleaned_data.get('amount'):
            return True
        return super()._should_delete_form(form)

    def clean(self):
        """Validate rules on the transaction content."""
        if any(self.errors):
            return

        accounts = 0
        total = 0
        for form in self.forms:
            # skip deleted form from validation
            if self.can_delete and self._should_delete_form(form):
                continue

            if form.cleaned_data.get('account'):
                accounts += 1

            total += form.cleaned_data.get('amount', 0)

        if not accounts:
            raise ValidationError("The transaction doesn't write in any accounts.")

        if total != 0:
            raise ValidationError(f"Credits and debits mismatch: {total}")


class TransactionTransferForm(forms.ModelForm):
    """
    Special form transfering amounts across budgets.
    It creates 1 transaction on each budget using a transfer account.
    """
    class Meta:
        model = Transaction
        fields = ('date', 'budget', 'notes')
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

    account = forms.ModelChoiceField(required=True, empty_label = '-- Account --',
                                     queryset=Account.objects.all())
    amount = forms.FloatField(required=True, label="Amount",
                              widget=forms.NumberInput(attrs={'placeholder': 'Amount'}))
    # add a second budget
    target = forms.ModelChoiceField(required=True, empty_label = '-- Destination --',
                                    queryset=Budget.objects.filter(status='O'))

    template_name = 'bookkeeper/forms/transaction_transfer_form.html'

    def __init__(self, *args, **kwargs):
        """Change model fields behavior."""
        super().__init__(*args, **kwargs)
        self.fields['budget'].empty_label = '-- Origin --'
        self.fields['budget'].required = True
        self.fields['budget'].queryset = Budget.objects.filter(status='O')
        self.fields['date'].initial = datetime.today()

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['budget'] == cleaned_data['target']:
            raise ValidationError('Origin and destination are the same.')

        # set payee
        cleaned_data['payee'] = 'internal transfer'
        return cleaned_data

    @transaction.atomic
    def save(self):
        """Create the two transactions to make the transfer."""
        # create the first transaction
        instance = super().save(commit=False)
        instance.payee = self.cleaned_data['payee']
        instance.save()
        instance.add_postings(
            TransactionType.temporary_transfer(
                self.cleaned_data['amount'],
                self.cleaned_data['account'].number,
            )
        )
        # create the second transaction from the first
        opposite = instance
        opposite.pk = None
        opposite.payee = self.cleaned_data['payee']
        opposite.budget = self.cleaned_data['target']
        opposite.save()
        opposite.add_postings(
            TransactionType.temporary_transfer(
                -self.cleaned_data['amount'],
                self.cleaned_data['account'].number,
            )
        )
        # validate before committing
        instance.clean()
        opposite.clean()

        # return the transaction writing in the destination account
        return opposite


class TransactionRouterForm(forms.Form):
    """
    Form keeping the mapping between the selected form and its class.
    The form itself has no use for validation.
    """
    _mapping = {
        'sale': TransactionSaleForm,
        'outsourcing': TransactionOutsourcingForm,
        'general': TransactionGeneralForm,
        'defrayal': TransactionDefrayalForm,
        'vat_expense': TransactionVatExpenseForm,
        'vat_credit': TransactionVatCreditForm,
        'tax_expense': TransactionTaxExpenseForm,
        'transfer': TransactionTransferForm,
        'manual': TransactionManualForm,
    }

    # FIXME: build the field from the mapping to avoid repetition
    type = forms.ChoiceField(required=True, choices=(
        ('sale', 'Client sale'),
        ('outsourcing', 'Outsourcing expense'),
        ('general', 'General expense'),
        ('defrayal', 'Expense claim'),
        ('vat_expense', 'Vat expense'),
        ('vat_credit', 'Vat credit'),
        ('tax_expense', 'Tax expense'),
        ('transfer', 'Transfer between budgets'),
        ('manual', 'Manual transaction'),
    ))

    @classmethod
    def get_form_class(cls, _type):
        try:
            return cls._mapping[_type]
        except KeyError:
            return TransactionManualForm


class TransactionSearchForm(forms.Form):
    """Transaction search form."""
    template_name = 'bookkeeper/forms/transaction_search_form.html'

    search = forms.CharField(required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Search...'}))
    budget = forms.ChoiceField(required=False, choices=[('','')])

bookkeeper/forms/transactiongroup.py
from django import forms
from django.core.exceptions import ValidationError
from django.db.transaction import atomic
from bookkeeper.models import Transaction, TransactionGroup, Budget, Posting
from bookkeeper.exceptions import *


class TransactionGroupBaseForm(forms.ModelForm):
    """
    Form providing the instance object of the group
    and the ID field used for all actions regarding transaction grouping.
    """
    class Meta:
        model = TransactionGroup
        fields = ()

    # group management fields
    id = forms.CharField(required=True, widget=forms.HiddenInput())

    def save(self):
        """Nothing to do on the TransactionGroup itself."""
        pass

    @classmethod
    def get_form_class(cls, querydict):
        """
        Identify the proper TransactionGroup form subclass to use
        by extracting the prefix from the POST QueryDict.
        """
        field = next(iter(querydict)).split('-')[0]
        mapping = {
            'add': TransactionGroupAddForm,
            'delete': TransactionGroupDeleteForm,
            'promote': TransactionGroupPromoteForm,
        }
        return mapping[field]


class TransactionGroupAddForm(TransactionGroupBaseForm):
    prefix = 'add'

    def clean(self):
        """Validate the transaction to add to the group."""
        cleaned_data = super().clean()
        transaction = Transaction.objects.get(pk=cleaned_data.pop('id'))

        # check if transaction to add is available
        if transaction.group:
            raise ValidationError('This transaction is already part of another group', code='invalid')

        # add the transaction to the group (with validation)
        self.instance.add_safe(transaction)


class TransactionGroupPromoteForm(TransactionGroupBaseForm):
    prefix = 'promote'

    def clean(self):
        """Promote the temporary transaction in an operation and add it to the group."""
        cleaned_data = super().clean()
        transaction = Transaction.objects.get(pk=cleaned_data.pop('id'))

        try:
            transaction.postings.get(account__number=471)
        except:
            raise ValidationError("This operation is already reconciled", code='invalid')

        # run the validation
        try:
            reconciliation_account = self.instance.check_reconciliation_account()
        except AccountingValidationError:
            raise ValidationError('Impossible to find how to match this operation.')
        try:
            budget = self.instance.check_budget()
        except AccountingValidationError:
            raise ValidationError('This operation needs to match a budget within the group.')

        # replace the temporary account with the reconciliation account
        # and attach the transaction to the group.
        with atomic():
            transaction.promote(reconciliation_account, budget)
            self.instance.add_safe(transaction)


class TransactionGroupDeleteForm(TransactionGroupBaseForm):
    prefix = 'delete'

    def clean(self):
        """
        Remove the transaction from the group.
        If the transaction is an operation it deletes it to revert the action of the promotion.
        """
        cleaned_data = super().clean()
        transaction = Transaction.objects.get(pk=cleaned_data.pop('id'))

        # check if the transaction to remove is part of the group
        if not self.instance.transactions.filter(pk=transaction.pk).exists():
            raise ValidationError('The transaction is not part of the current group', code='invalid')

        # demote operation
        if not transaction.clearable:
            transaction.demote()

        # remove transacton from group
        self.instance.transactions.remove(transaction)

bookkeeper/templates/bookkeeper/forms/transaction_base_form.html
{% load widget_tweaks %}

{% if form.non_field_errors %}
  {% for error in form.non_field_errors %}
  {{ error }}
  {% endfor %}
{% endif %}

<div class="grid">
  <div>
    <h6>Informations</h6>

    {{ form.budget|add_error_attr:"aria-invalid:true" }}
    <div style="color: red">{{ form.budget.errors|first|escape }}</div>

    {{ form.date|add_error_attr:"aria-invalid:true" }}
    <div style="color: red">{{ form.date.evidence.errors|first|escape }}</div>

    {{ form.payee|add_error_attr:"aria-invalid:true" }}
    <div style="color: red">{{ form.payee.errors|first|escape }}</div>

    <h6>Evidence</h6>

    {{ form.evidence_ref|add_error_attr:"aria-invalid:true" }}
    <div style="color: red">{{ form.evidence_ref.errors|first|escape }}</div>

    {{ form.evidence|add_error_attr:"aria-invalid:true" }}
    <div style="color: red">{{ form.evidence.errors|first|escape }}</div>
  </div>

  <div>
    <h6>Amounts</h6>
    {% block content %}{% endblock %}
  </div>
</div>

<details>
  <summary>Notes</summary>
  {{ form.notes|add_error_attr:"aria-invalid:true" }}
</details>

bookkeeper/templates/bookkeeper/forms/transaction_edit_form.html
{% load widget_tweaks %}

{% if form.non_field_errors %}
  {% for error in form.non_field_errors %}
  {{ error }}
  {% endfor %}
{% endif %}

<div class="grid">
  <div>
    <h6>Informations</h6>

    {{ form.budget|add_error_attr:"aria-invalid:true" }}
    <div style="color: red">{{ form.budget.errors|first|escape }}</div>

    {{ form.date|add_error_attr:"aria-invalid:true" }}
    <div style="color: red">{{ form.date.evidence.errors|first|escape }}</div>

    {{ form.payee|add_error_attr:"aria-invalid:true" }}
    <div style="color: red">{{ form.payee.errors|first|escape }}</div>

    <h6>Evidence</h6>

    {{ form.evidence_ref|add_error_attr:"aria-invalid:true" }}
    <div style="color: red">{{ form.evidence_ref.errors|first|escape }}</div>

    {{ form.evidence|add_error_attr:"aria-invalid:true" }}
    <div style="color: red">{{ form.evidence.errors|first|escape }}</div>
  </div>

  <div>
    <h6>Amounts</h6>
    {% if formset %}

    <div style="color: red">{{ formset.non_form_errors|first|escape }}</div>
    {{ formset.management_form }}
    <ul id="postings">
      {% for pform in formset %}
      <li style="display: inline-flex;">
          {{ pform.id|add_error_attr:"aria-invalid:true" }}
          {{ pform.account|add_error_attr:"aria-invalid:true" }}
          {{ pform.amount|add_error_attr:"aria-invalid:true" }}
      </li>
      {% endfor %}
    </ul>
    <a href="" role="button" id="add-posting" class="secondary"
      style="float: right;">Add entry</a>

    <script type="text/javascript">
        // adding new postings
        document.getElementById("add-posting").addEventListener('click', function(event) {
          event.preventDefault();
          let listPostings = document.querySelector("#postings");
          let totalForms = document.querySelector("#id_postings-TOTAL_FORMS");
          // clone the template form
          let newPosting = document.querySelector("#postings > li:last-child").cloneNode(true);
          // insert the new form at the en of the list
          newPosting.innerHTML = newPosting.innerHTML.replace(RegExp(`postings-(\\d){1}-`, 'g'), `postings-${totalForms.value}-`);
          listPostings.insertAdjacentElement('beforeend', newPosting);
          // increment totalForms
          totalForms.setAttribute('value', parseInt(totalForms.value) + 1)
        });
    </script>

    {% else %}

      {{ form.amount|add_error_attr:"aria-invalid:true" }}
      <div style="color: red">{{ form.amount.errors|first|escape }}</div>

      {{ form.bp|add_error_attr:"aria-invalid:true" }}
    <div style="color: red">{{ form.bp.errors|first|escape }}</div>

      {{ form.vat|add_error_attr:"aria-invalid:true" }}
    <div style="color: red">{{ form.vat.errors|first|escape }}</div>

    {% endif %}
  </div>
</div>

<details>
  <summary>Notes</summary>
  {{ form.notes|add_error_attr:"aria-invalid:true" }}
</details>

bookkeeper/templates/bookkeeper/forms/transaction_manual_form.html
{% extends "./transaction_base_form.html" %}
{% load widget_tweaks %}
{% load static %}

{% block content %}

    <div style="color: red">{{ formset.non_form_errors|first|escape }}</div>
    {{ formset.management_form }}
    <ul id="postings">
      {% for pform in formset %}
      <li style="display: inline-flex;">
          {{ pform.id|add_error_attr:"aria-invalid:true" }}
          {{ pform.account|add_error_attr:"aria-invalid:true" }}
          {{ pform.amount|add_error_attr:"aria-invalid:true" }}
      </li>
      {% endfor %}
    </ul>
    <a href="" role="button" id="add-posting" class="secondary" style="float: right;"
      >+</a>
    <script type="text/javascript">
        // adding new postings
        document.getElementById("add-posting").addEventListener('click', function(event) {
          event.preventDefault();
          let listPostings = document.querySelector("#postings");
          let totalForms = document.querySelector("#id_postings-TOTAL_FORMS");
          // clone the template form
          let newPosting = document.querySelector("#postings > li:last-child").cloneNode(true);
          // insert the new form at the en of the list
          newPosting.innerHTML = newPosting.innerHTML.replace(RegExp(`postings-(\\d){1}-`, 'g'), `postings-${totalForms.value}-`);
          listPostings.insertAdjacentElement('beforeend', newPosting);
          // increment totalForms
          totalForms.setAttribute('value', parseInt(totalForms.value) + 1)
        });
    </script>

{% endblock %}

bookkeeper/templates/bookkeeper/forms/transaction_search_form.html
{% load static %}
<div>
  <div class="grid">
    {{ form.budget }}
    {{ form.year }}
    {{ form.search }}
  </div>
  <fieldset>
    <img class="htmx-indicator" src="{% static 'bookkeeper/bars.svg' %}" style="height: 30px;">
    <label for="{{ form.pending.id_for_label }}" style="display: inline-block;">
      {{ form.pending }}
      {{ form.pending.label }}
    </label>
    <label for="{{ form.proof.id_for_label }}" style="display: inline-block;">
      {{ form.proof }}
      {{ form.proof.label }}
    </label>
    <label for="{{ form.record.id_for_label }}" style="display: inline-block;">
      {{ form.record }}
      {{ form.record.label }}
    </label>
    <label for="{{ form.operation.id_for_label }}" style="display: inline-block;">
      {{ form.operation }}
      {{ form.operation.label }}
    </label>
    <label for="{{ form.group.id_for_label }}" style="display: inline-block;">
      {{ form.group }}
      {{ form.group.label }}
    </label>
  </fieldset>
</div>

bookkeeper/templates/bookkeeper/forms/transaction_simple_form.html
{% extends "./transaction_base_form.html" %}
{% load widget_tweaks %}

{% block content %}

  {{ form.amount|add_error_attr:"aria-invalid:true" }}
  <div style="color: red">{{ form.amount.errors|first|escape }}</div>

  <div class="grid">
    {{ form.vat|add_error_attr:"aria-invalid:true" }}
    <select
        _="on change
              set amount to the (value of <input#id_amount/>) as a Float
              set coef to the (first <option:checked/> in me).value as a Float
              put amount * coef into the (value of <input#id_vat/>)"
      >
      <option disabled selected value>%</option>
      <option value="0.2">20%</option>
      <option value="0.1">10%</option>
      <option value="0.055">5.5%</option>
      <option value="0">0%</option>
    </select>
  </div>
  <div style="color: red">{{ form.vat.errors|first|escape }}</div>

{% endblock %}

bookkeeper/templates/bookkeeper/forms/transaction_transfer_form.html
{% load widget_tweaks %}

{% if form.non_field_errors %}
<div style="color: red;">
  {% for error in form.non_field_errors %}
  {{ error }}
  {% endfor %}
</div>
{% endif %}

<div class="grid">
  {{ form.budget }}
  {{ form.target }}
</div>

<div class="grid">
  {{ form.date|add_error_attr:"aria-invalid:true" }}
  {{ form.amount|add_error_attr:"aria-invalid:true" }}
  {{ form.account|add_error_attr:"aria-invalid:true" }}
</div>

<details>
  <summary>Notes</summary>
  {{ form.notes|add_error_attr:"aria-invalid:true" }}
</details>